#!/usr/bin/env bash
THIRD_PARTY=`pwd`/third_party
UNIFONT_VERSION=10.0.05

set -ex

# NASM
wget https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz -O "$THIRD_PARTY/nasm.tar.xz"
mkdir -p "$THIRD_PARTY/nasm"
tar -xvf "$THIRD_PARTY/nasm.tar.xz" -C "$THIRD_PARTY/nasm" --strip-components=1

# TCC
wget http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.26.tar.bz2 -O "$THIRD_PARTY/tcc.tar.bz2"
mkdir -p "$THIRD_PARTY/tcc"
tar -xvjf "$THIRD_PARTY/tcc.tar.bz2" -C "$THIRD_PARTY/tcc" --strip-components=1

# GRUB
wget ftp://ftp.gnu.org/gnu/grub/grub-2.02.tar.xz -O "$THIRD_PARTY/grub.tar.xz"
mkdir -p "$THIRD_PARTY/grub"
tar -xvf "$THIRD_PARTY/grub.tar.xz" -C "$THIRD_PARTY/grub" --strip-components=1

# Unifont
wget http://unifoundry.com/pub/unifont-$UNIFONT_VERSION/unifont-$UNIFONT_VERSION.tar.gz -O "$THIRD_PARTY/unifont.tar.gz"
cd "$THIRD_PARTY"
tar xvf "$THIRD_PARTY/unifont.tar.gz"
cd ..
